name: (CD) Webwinkel

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Angular CLI
      run: | 
        npm install -g @angular/cli
        pwd
        ls -l

    - name: Install dependencies
      run: | 
        cd FE/winkel-app
        npm install
        ls -l
      
    - name: Build
      run: |
        cd FE/winkel-app        
        ng build --configuration=production
        ls -l

    - name: Configure Git
      run: |
        git config --global user.email "eburdo@gmail.com"
        git config --global user.name "Eugeny"
        
    - name: Deploy
      run: |
        cd FE/winkel-app/dist/winkel-app
        git clone https://${{ secrets.WEB_APP_TOKEN }}@api.glitch.com/git/winkel-app
        rm winkel-app/browser/*
        cp browser/* winkel-app/browser
        cd winkel-app
        ls -l
        git add .
        echo "add done"
        git commit -m "deploy new version"
        echo "commit done"
        git push
        echo "push done"
