name: (CI) NodeJS with Webpack

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Angular CLI
      run: | 
        npm install -g @angular/cli
        pwd
        ls -l

    - name: Install dependencies
      run: | 
        cd FE/winkel-app
        npm install
        ls -l
      
    - name: Build
      run: |
        cd FE/winkel-app        
        ng build --configuration=production
        ls -l

    - name: Test
      run: |
        cd FE/winkel-app        
        npm run test-headless
        echo "Test Completed"
        ls -l
